const PROJECTS_DATA = [
    {
        id: 1,
        name: 'Restaurant Website',
        desc: 'The Restaurant website is created with Html5, Css3 and scrollreveal plugin for scrolling animations.',
        image: '/projects/restaurant.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://vaibhav-bhoir.github.io/therestaurant/',
        github: 'https://github.com/vaibhav-bhoir/therestaurant',
        type: 'Website',
    },
    {
        id: 2,
        name: 'Brochure website',
        desc: 'This website is made using html, css, bootstrap and little bit JavaScript.It has smooth scrolling effects and also has scroll to top button.',
        image: '/projects/brochure.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://vaibhav-bhoir.github.io/responsivesite/',
        github: 'https://github.com/vaibhav-bhoir/responsivesite',
        type: 'Website',
    },
    {
        id: 3,
        name: 'E-commerce Website',
        desc: 'This website i created using bootstrap framework, SASS and vanilla JavaScript. This site included product, all product , product details page.It also has cart page where we can see how many items are added to the cart.',
        image: '/projects/ecommerce.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://vaibhav-bhoir.github.io/ecommerce/',
        github: 'https://github.com/vaibhav-bhoir/ecommerce',
        type: 'Website',
    },
    {
        id: 4,
        name: 'Landing Page',
        desc: 'Simple Landing Page Created using HTML, CSS and Bootstrap.',
        image: '/projects/landing.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://vaibhav-bhoir.github.io/landingpage/',
        github: 'https://github.com/vaibhav-bhoir/landingpage',
        type: 'Website',
    },
    {
        id: 5,
        name: 'Registration and Login',
        desc: 'This is a user login and registration app using Node.js, Express, Passport, Mongoose, EJS and some other packages.',
        image: '/projects/registartion-login.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: '#',
        github: 'https://github.com/vaibhav-bhoir/registrationlogin',
        type: 'Website',
    },
    {
        id: 6,
        name: 'My Portfolio',
        desc: 'lorem ipsum lorem ipsum lorem ipsdum lorem ipsum',
        image: '/projects/code.jpg',
        tech: [{ class: '/icons/html5.svg', name: 'HTML' }, { class: '/icons/css.svg', name: 'CSS' }, { class: '/icons/javascript.svg', name: 'JS' }, { class: '/icons/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://vaibhav-bhoir.github.io/react-portfolio',
        github: 'https://github.com/vaibhav-bhoir/react-portfolio',
        type: 'Website',
    },
]

export default PROJECTS_DATA